### ISSUE TITLE
unable to run in command line mode

### ISSUE THREAD

**Issue by mgyver** [peci1/RadioControl#2]
Dear developer,

I installed your app via Microsoft Store and can run it via gui successfully to both wifi and bluetooth.
I kept the gui running, opened a dos window and run commands as suggested, but it din't work.
Here's what happened:
--------------------------
Microsoft Windows [Version 10.0.17763.316]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\mgyver> radiocontrol
'radiocontrol' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\mgyver> radiocontrol.exe 0 off
'radiocontrol.exe' is not recognized as an internal or external command,
operable program or batch file.**

--------------------------

Would you guide me how to make it work, please ?

I thought this would be simple, working out of the box because it's quite straight forward..
...maybe I did something wrong ?

Thanks for your amazing app.

**Comment by peci1** [comment]
Hmm, this is weird. Windows itself should take care about making this command available when you install the app.

I tried removing and reinstalling the app on my computer, and indeed the command disappeared when I uninstalled it, and it came back when I reinstalled the app.

On my computer, the binary it runs is %USERPROFILE%\AppData\Local\Microsoft\WindowsApps\radiocontrol.EXE, so you may try with the absolute path, or searching around for the correct binary.

**Comment by mgyver** [comment]
Thank you very much .. it's working perfectly now.

You app is tiny but very useful and clears the limitation of an ahk script which i had been using for so long  :) 

Thanks a lot again.

**Comment by peci1** [comment]
Good to hear that ;) So does it work now even with just the command, or only with the absolute path?

Also, are you aware of [the cmdlet](https://superuser.com/a/1293303/255660) that can turn radios on/off completely without installing anything? This is what I'm using right now.

**Comment by mgyver** [comment]
I had to put the absolute path into my environment variables to make it work.

For the cmdlet you suggested, it works great for the bluetooth.
How about Wi-Fi .. can the cmdlet control Wi-Fi ? 
If so, could you please suggest on the how-to. 

Thanks for another interesting tip.

**Comment by peci1** [comment]
I suppose the cmdlet can also work with wifi and any other radios. Just play with the code, I'd start by editing the third line from bottom:

    $bluetooth = $radios | ? { $_.Kind -eq 'Bluetooth' }

**Comment by mgyver** [comment]
Thank you very much, 
...especially the way you guided helps a lot to improve my learning skill on modifying the codes. 

I successfully made the cmdlet work (on WiFi) by digging deeper and found this page : https://docs.microsoft.com/en-us/uwp/api/windows.devices.radios.radiokind

👍 😄
