### ISSUE TITLE
[feature request] an option to reconnect the hardware to the computer (to solve error 45)

### ISSUE THREAD

**Issue by WiliTest** [peci1/RadioControl#3]
Thanks for your app! 
My Bluetooth hardware has been disconnected by the computer (using the PowerShell command `Disable-NetAdapter *` and then `Enable-NetAdapter *`: it was supposed to just turn OFF/ON all net adapters (including Bluetooth), but it actually disconnected the Bluetooth hardware). 

I tried to turn it ON using your app `radiocontrol bluetooth ON` but it sends  `Radio Bluetooth/0 was not found`.

By chance, do you know how to reconnect a device that has been disconnected?

**Comment by peci1** [comment]
Hi, this app really works only with connected devices. If you disconnected it, you have to find a different way to get it back. I'd suggest to disconnect this device from your computer (manually) and reconnect it again.

**Comment by WiliTest** [comment]
Thanks for your reply and your advice! The Bluetooth hardware (that has been disconnected by a "Disable-NetAdapter *") is inside the laptop, so not so easy to do it. 
Anyway, thanks a lot for your app!
