### ISSUE TITLE
Cannot access application from Task Scheduler

### ISSUE THREAD

**Issue by masi0** [peci1/RadioControl#4]
I want to create a task to run radiocontrol when laptop goes to sleep, e.g. event 506 triggers it
Unfortunately I cant provide a path to %appdata% location as per your suggestion / getting error - file cannot be accessed by the system

**Comment by peci1** [comment]
Maybe you have to expand the variable in the path? I.e., you can open an Explorer window, press Ctrl+L to enter a path, and paste the path to the app: `%USERPROFILE%\...`... It should then go to the application folder, and if you press Ctrl+L again, you get the expanded path. Try to use that in the scheduled task.

**Comment by nirvine** [comment]
I have the same error with Task Scheduler. I cannot move or copy the file, as I get the "Cannot be accessed by the System" error if I try that. App works fine when started as a standalone program. I have tried using the full path, as well as using shortcuts.

**Comment by peci1** [comment]
You probably have to expand the  `USERPROFILE` variable to an actual path. To figure out the content of the variable, open a cmd console (Win+R, type `cmd`), and type:

```bat
echo "%USERPROFILE%"
rem it will output a path like this; use it instead of the variable: "C:\Users\Martin Pecka"
```

**Comment by nirvine** [comment]
I have tried that. The task fails to run.

**Comment by peci1** [comment]
When creating the task, do you put the program arguments to the separate field for arguments, right?

![obrazek](https://user-images.githubusercontent.com/182533/211255299-1f25aa1c-cce4-4901-8282-81544cb11b4d.png)

**Comment by nirvine** [comment]
I have been trying to use these instructions to schedule the bluetooth on and off at specific times - https://www.addictivetips.com/windows-tips/turn-bluetooth-on-off-on-lock-unlock-windows-10/

So I had no arguments in the Task Scheduler - they were added in the bat scripts. 

But none of that explains why, when trying to add the file using the browse option on the Actions tab, I get the error "Cannot be accessed by the System". I also get this error if I try to move the file to a different location.

**Comment by peci1** [comment]
So do you actually call radiocontrolcmd via a bat file or directly? Could you put together exact steps to reproduce?

**Comment by nirvine** [comment]
I now have this working correctly. I think the problem was because I had used the option to "Create Task" rather than "Create Basic Task" in the Task Scheduler. Thank you for your patience with me!

**Comment by peci1** [comment]
Great, thanks for letting me know!
